name: Master Merge Deployment

on:
  push:
    branches:
      - master

jobs:
  check-code-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linting
        run: docker compose run dev npm run lint:check

  check-code-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run format check
        run: docker compose run dev npm run format:check

  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: docker compose run dev npm run test

  build-push-prod-image:
    needs: [check-code-lint, check-code-format, run-test-cases]
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Docker login
        run: docker info | grep Username

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push with commit hash tag
        run: |
          docker compose build prod
          docker tag ci-cd-pipeline-prod saqib29/ci-cd-dockerized-nodejs-aws-ec2:${{ steps.vars.outputs.sha_short }}
          docker push saqib29/ci-cd-dockerized-nodejs-aws-ec2:${{ steps.vars.outputs.sha_short }}
